<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ServicesChecker.UI\ServicesChecker.UI.csproj" />
    <ProjectReference Include="..\..\src\ServicesChecker.Infrastructure\ServicesChecker.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\ServicesChecker.Application\ServicesChecker.Application.csproj" />
    <ProjectReference Include="..\..\src\ServicesChecker.Domain\ServicesChecker.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>